### ISSUE TITLE
Looking to Add 'return' functionality to functions.

### ISSUE THREAD

**Issue by woflydev** [TechStudent11/Skate#2]
Just as the title says. Working on it through a local version downloaded from the repo. Don't know if opening an issue is the right way to do this, but that's what it says on the ReadMe, so that's what I did.

**Comment by TechStudent10** [comment]
This is something that has been on my mind for a long time. Just can't think of a way to implement it. I will find a way eventually.

**Comment by woflydev** [comment]
I'm close to having it working, if you're interested.

**Comment by TechStudent10** [comment]
Could you share your implementation, please?

**Comment by TechStudent10** [comment]
If you do have an early (working) version, you could push it to your fork for me to read, if you like.

**Comment by TechStudent10** [comment]
Closing due to no response from author.
